set-option -g history-limit 50000
#set-option -g status off
set-option -s escape-time 0

set-option -g prefix C-Space
bind-key C-Space send-prefix

bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R

bind-key C-p previous-window
bind-key C-n next-window

bind-key C-f display-popup -EE -w 80% -h 80% -xC -yC "tmux-sessionizer"
bind-key C-r source-file ~/.tmux.conf \; display-message "Config reloaded!"
